🔀 :: (#13) PICK ADMIN 드롭다운 제작
DSM-PICK/PICK2023_FRONT_ADMIN pull request #15
Opened 2023-02-17 12:26 UTC by inung1004

### 작업 상세 내용

- [x] 드롭다운 제작

### 생각해볼 문제
closes #13

2023-02-18 07:42 UTC, potatovllage commented on src/common/dropDown/index.tsx
> +const DropDown = ({
드롭다운의 아이템들이 바뀌면 그 아이템이 무엇이냐에 따라서 api 호출 할 때 함수 인자값으로 들어가거나 
그 아이템이 무엇인지 중요할 것 같은데 그 아이템을 드롭다운 컴포넌트보다 상위 컴포넌트로 어떻게 보내는지 잘 모르겠습니다

2023-02-18 08:40 UTC, inung1004 commented on src/common/dropDown/index.tsx
> +const DropDown = ({
넵 수정했습니다..!!

2023-02-19 15:57 UTC, potatovllage approved these changes

2023-02-20 05:50 UTC, hyeyeonchurros reviewed
드롭다운 눌렀을 때 스타일 바뀌는데 그것만 추가해조

일반 드롭다운은 선택했을 때 border가 메인컬러, text는 gray800이나 gray900 사용하면 되고
출결 상태에서의 드롭다운은 눌러도 스타일 안바뀌어

isClick 사용하면 될 것 같아 수고해써

2023-02-21 05:35 UTC, harry-cc requested changes

2023-02-21 05:35 UTC, harry-cc commented on src/components/common/dropDown/index.tsx
> +  const [isClick, setIsCLick] = useState<boolean>(false);
setIsCLick => setIsClick

2023-02-21 05:35 UTC, harry-cc commented on src/components/common/dropDown/index.tsx
> +        setFontColor("#3F3C42");
보니까 바꾸는 state들은 같은 종류 3개 고정인거 같은데 함수로 묶는 것도 한번 고려해봐주세요

2023-02-21 05:35 UTC, harry-cc commented on src/components/common/dropDown/index.tsx
> +        setFontColor("#9F62F5");
저번에 코드 세팅된거 살펴봤을 때 
const theme = useTheme()
theme.colors.뭐시기
이런식으로 쓸 수 있는 훅이 있던데 요 값들 그거 써서 대체할 수 있는지 시도해봐주세요
그 전에 아무한테 이거 써도 되는 건지 여쭤보시고
값이 안맞을수도 있으니 시도만..

2023-02-21 05:36 UTC, harry-cc commented on src/components/common/dropDown/index.tsx
> +  const onChange = async (item: ItemType) => {
얘는 async 쓴 이유가 따로 있을까요?(단순 질문)

2023-02-22 11:45 UTC, inung1004 commented on src/components/common/dropDown/index.tsx
> +  const onChange = async (item: ItemType) => {
전에 async await 을 쓸 일이 있어서 썼다가 미처 확인 못 하고 안 지웠네요.. 핳핳

2023-02-22 12:18 UTC, justinlee05 approved these changes
굳

2023-02-22 12:32 UTC, merged