🔀 :: (#26) PICK ADMIN 인원변경(동아리) 퍼블리싱
DSM-PICK/PICK2023_FRONT_ADMIN pull request #32
Opened 2023-03-03 08:11 UTC by Aodtn

### 작업 개요

### 작업 상세 내용

- [ ] 인원병경(동아리) 페이지 퍼블리싱

### 생각해볼 문제

modal 추가

2023-03-03 08:15 UTC, hanbi2256 approved these changes
good

2023-03-03 08:29 UTC, justinlee05 requested changes
리뷰 확인 부탁드립니다.

2023-03-03 08:29 UTC, justinlee05 commented on src/components/club/member.tsx
> +  background-color: #fff;
theme 사용 부탁드립니다.

2023-03-03 08:29 UTC, justinlee05 commented on src/components/club/menu.tsx
> +  background-color: #fff;
theme 사용 부탁드립니다.

2023-03-03 08:29 UTC, justinlee05 commented on src/components/club/DropDwonItem.ts
> +export const layerDropDownItem = [
파일 이름 DropDwonItem.ts => DropDownItem.ts

2023-03-03 08:29 UTC, justinlee05 commented on src/components/club/index.tsx
> +  const membarList = [
membar => member

2023-03-03 08:29 UTC, justinlee05 commented on src/components/club/index.tsx
> +          <Member data={list} />
props를 data:{...props} 이런 식으로 2중으로 받는 것보다 처음부터 spread 연산자로 넘기면 Member 컴포넌트 내에서 비구조화 할당을 한 번만 수행해도 될 것 같은데 한 번 고려해주세요.

2023-03-03 08:29 UTC, justinlee05 commented on src/components/club/member.tsx
> +    console.log("동아리장 위임");
로그 제거 부탁드립니다.
camelCase로 네이밍 바꿔주세요.

2023-03-03 10:21 UTC, hyeyeonchurros requested changes
<img width="1380" alt="cxnskdj" src="https://user-images.githubusercontent.com/81298254/222695278-6beba26e-2cf9-4069-9c3e-9c441b17d7cf.png">
1. 드롭다운 아래 요소 왼쪽 정렬해주세요
2. 호버 효과가 있는데 아래 border-radius를 제거하거나 아예 효과를 지워주세요

2023-03-03 10:34 UTC, hyeyeonchurros requested changes

2023-03-03 10:34 UTC, hyeyeonchurros commented on src/components/club/index.tsx
> +          <SubTitle>{name}(장연순선생님 담당)</SubTitle>
선생님 성함을 불러오는 API가 없길래 백엔드한테 물어본 상태입니다
백엔드쪽에서 말해주면 전해드릴게요

2023-03-03 10:34 UTC, hyeyeonchurros commented on src/pages/club/index.tsx
> +export default ClubPage;
component/club/index.tsx 파일 지우고 여기서 렌더링해주세요

2023-03-03 11:43 UTC, inung1004 commented on src/pages/club/index.tsx
> +          <SubTitle>{name}(장연순선생님 담당)</SubTitle>
여기 (장연순선생님 담당)은 왜 props로 안 넘겨주고 직접 적으셨나요?

2023-03-03 11:43 UTC, inung1004 commented on src/components/club/member.tsx
> +  };
똑같은 일을 하는 함수인데 왜 굳이 두 개인 거죠? onClick함수 하나만 쓰는게 좋을 거 같아요 아 아니면 그 clubClick={()=> setOpenMenu(!openMenu)} 이런 식으로 하는 방법도 좋을 거 같아요

2023-03-03 11:43 UTC, inung1004 commented on src/pages/club/index.tsx
> +  const name = "세미나실 4-1";
드롭다운에서 받아온 값으로 띄어주는게 좋을 거 같아요

2023-03-03 13:52 UTC, Aodtn commented on src/components/club/member.tsx
> +  };
이거는 더보기메뉴 눌렀을 때 '동아리장위임'이랑 '동아리변경'하려고 만들어놓은 함수구요. 모달을 추가 해야 합니다.

2023-03-03 18:24 UTC, justinlee05 approved these changes
굳

2023-03-04 12:27 UTC, hyeyeonchurros approved these changes

2023-03-05 05:13 UTC, merged